METHOD:
  NAME: "BayesMMRL"
  FAMILY: internal_adaptation
  EXEC_MODE: online


BAYES_MMRL:

  PREC: amp
  ALPHA: 0.5
  REG_WEIGHT: 0.5

  N_REP_TOKENS: 5
  REP_LAYERS: [6, 7, 8, 9, 10, 11, 12]
  REP_DIM: 512

  BAYES_TARGET: "rep_tokens"   # rep_tokens | proj_rep

  # MC
  N_MC_TRAIN: 3
  N_MC_TEST: 10

  # Mean-main + MC-rep
  EVAL_MODE: "mean_main_mc_rep"   # posterior_mean | mc_predictive | mean_plus_mc | mean_main_mc_rep
  EVAL_USE_POSTERIOR_MEAN: False
  EVAL_AGGREGATION: "prob_mean"  # prob_mean | logit_mean

  # posterior over R
  REP_SIGMA_MODE: "diagonal"        # global | per_token | diagonal | matrix_normal_diag | matrix_normal_diag_lowrank
  REP_PRIOR_MODE: "zero"          # zero | clip_joint
  REP_PRIOR_STD: 0.05
  KL_WARMUP_EPOCHS: 5
  REP_KL_WEIGHT: 1e-3



  # ----- Matrix-Normal specific -----
  REP_MN_ENFORCE_TRACE: True
  REP_MN_LOWRANK_RANK: 8


  # only used when BAYES_TARGET: proj_rep
  PROJ_REP_SIGMA_MODE: "row"
  PROJ_REP_PRIOR_MODE: "clip_proj"
  PROJ_REP_PRIOR_STD: 0.01
  PROJ_REP_KL_WEIGHT: 1.0e-6
