METHOD:
  NAME: "BayesMMRL"
  FAMILY: internal_adaptation
  EXEC_MODE: online


BAYES_MMRL:
  PREC: amp
  ALPHA: 0.6
  REG_WEIGHT: 0.5
  N_REP_TOKENS: 5
  REP_LAYERS: [6, 7, 8, 9, 10, 11, 12]
  REP_DIM: 512
  N_MC_TRAIN: 3
  N_MC_TEST: 10
  KL_WEIGHT: 5e-5
  PRIOR_STD: 0.01
  POSTERIOR_RHO_INIT: -3.9
  EVAL_USE_POSTERIOR_MEAN: True