METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  TAG: TR_grid

CLIP_ADAPTERS:
  PREC: amp
  TYPE: MP
  INIT: TR
  CONSTRAINT: none
  ENHANCED_BASE: none
  ALLOW_CACHE: true

  GRID_SEARCH: true
  GRID_SEARCH_SPLIT: val

  CACHE_REPS: 20
  CACHE_TRAIN_AUG: true
  CACHE_AGGREGATION: pool
  CACHE_POOL_EPOCH_SUBSAMPLE: true