CLIP_ADAPTERS:
  INIT: HBA_LR

  N_SAMPLES: 5
  N_TEST_SAMPLES: 50

  HBA_RANK: 4
  HBA_RHO: 1.0

  HBA_S0: 0.01
  HBA_S_MIN: 0.0001

  HBA_SUPPORT_INIT: True
  HBA_INIT_RESIDUAL: logmap
  HBA_INIT_STRENGTH: 1.0
  HBA_INIT_MAX_NORM: 5.0

  HBA_BETA: 0.00005
  BAYES_KL_SCALE: 1.0

  HBA_LAMBDA_B: 0.0
  HBA_LAMBDA_ORTH: 0.0001