METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  TAG: DEBA_J

CLIP_ADAPTERS:
  PREC: amp
  TYPE: MP
  INIT: DEBA
  CONSTRAINT: none
  ENHANCED_BASE: none
  ALLOW_CACHE: true

  N_SAMPLES: 3
  N_TEST_SAMPLES: 10

  BAYES_PRIOR_STD: 0.01
  BAYES_KL_SCALE: 1.0
  KL_WEIGHT: 0.0001

  DEBA_MODE: j
  DEBA_LAMBDA: 0.3

  DEBA_ALPHA0: 1.0
  DEBA_S_MIN: 1.0
  DEBA_S_MAX: 1000.0
  DEBA_S_AGG: weighted_mean
  DEBA_S_GRAD_SCALE: 0.0
  DEBA_EPS: 0.000001

  DEBA_EVAL_RETURN: dirichlet_mean # mc_predictive dirichlet_mean
  DEBA_DIRICHLET_ON_TRAIN_LOGITS: false

  CACHE_REPS: 20
  CACHE_TRAIN_AUG: true
  CACHE_AGGREGATION: pool
  CACHE_POOL_EPOCH_SUBSAMPLE: true

  GRID_SEARCH: false
  GRID_SEARCH_SPLIT: val