METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  TAG: CrossModal

CLIP_ADAPTERS:
  PREC: amp
  TYPE: MP
  INIT: CrossModal
  CONSTRAINT: none
  ENHANCED_BASE: none
  ALLOW_CACHE: true

  CROSS_MODAL_RESAMPLE_TEXT: true
  CROSS_MODAL_EPOCH_SUBSAMPLE: true

  GRID_SEARCH: false
  GRID_SEARCH_SPLIT: val

  CACHE_REPS: 20
  CACHE_TRAIN_AUG: true
  CACHE_AGGREGATION: pool
  CACHE_POOL_EPOCH_SUBSAMPLE: true