METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  EXEC_MODE: cache
  TAG: TipA-f-

CLIP_ADAPTERS:
  PREC: amp
  TYPE: MP
  INIT: TipA-f-
  CONSTRAINT: none
  ENHANCED_BASE: none
  ALLOW_CACHE: true

  CLAP_TIPA_TRAINABLE_CACHE: true
  CLAP_TIPA_RAW_AFFINITY: true
  CLAP_TIPA_ONE_EPOCH: true
  TIPA_F_GRID_EPOCHS: 20

  GRID_SEARCH: false
  GRID_SEARCH_SPLIT: val

  CACHE_REPS: 20
  CACHE_TRAIN_AUG: true