METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  EXEC_MODE: cache
  TAG: TR

CLIP_ADAPTERS:
  PREC: amp
  TYPE: MP
  INIT: TR
  CONSTRAINT: none
  ENHANCED_BASE: none
  ALLOW_CACHE: true

  GRID_SEARCH: false
  GRID_SEARCH_SPLIT: val

  CACHE_REPS: 20
  CACHE_TRAIN_AUG: true