METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  EXEC_MODE: cache

CLIP_ADAPTERS:
  PREC: fp32
  TYPE: MP
  INIT: ZS
  CONSTRAINT: none
  ENHANCED_BASE: none
  N_SAMPLES: 3
  ALLOW_CACHE: true
  KL_WEIGHT: 0.0001
