METHOD:
  NAME: ClipAdapters
  FAMILY: adapter
  EXEC_MODE: cache
  TAG: CLAP

CLIP_ADAPTERS:
  PREC: amp
  TYPE: MP
  INIT: ZS
  CONSTRAINT: l2
  ENHANCED_BASE: none
  ALLOW_CACHE: true

  GRID_SEARCH: false
  GRID_SEARCH_SPLIT: val

  CACHE_REPS: 20
  CACHE_TRAIN_AUG: true