METHOD:
  NAME: MMRLpp
  FAMILY: internal_adaptation
  EXEC_MODE: online

MMRLPP:
  PREC: amp
  ALPHA: 0.7
  BETA: 0.9
  REG_WEIGHT: 1.0
  N_REP_TOKENS: 5
  REP_LAYERS: [6, 7, 8, 9, 10, 11, 12]
  REP_DIM: 512
  PROJ_LORA_DIM: 64
  RES_LORA_DIM: 4
