METHOD:
  NAME: MMRLMix
  FAMILY: internal_adaptation
  EXEC_MODE: online

MMRL_MIX:
  PREC: amp
  ALPHA: 0.7
  REG_WEIGHT: 0.5
  LOSS_MAIN_WEIGHT: 1.0
  LOSS_REP_WEIGHT: 1.0
  LOSS_FUSE_WEIGHT: 0.2
  N_REP_TOKENS: 5
  REP_LAYERS: [6, 7, 8, 9, 10, 11, 12]
  REP_DIM: 512