METHOD:
  NAME: VCRMMMRL
  FAMILY: internal_adaptation
  EXEC_MODE: online

VCRM_MMRL:
  PREC: amp
  ALPHA: 0.7
  REG_WEIGHT: 0.5
  N_REP_TOKENS: 5
  REP_LAYERS: [6, 7, 8, 9, 10, 11, 12]
  REP_DIM: 512

  VCRM_CONTEXT_LAYER: 5
  VCRM_HIDDEN_DIM: 512
  VCRM_ETA: 0.1
  VCRM_DETACH_CONTEXT: True
  VCRM_MOD_WEIGHT: 0.0