from .base import BaseAdapter
from .random_probe import RandomProbeAdapter
from .zs_probe import ZeroShotProbeAdapter
from .task_residual import TaskResidualAdapter
from .clip_adapter import ClipAdapterResidual
from .tip_adapter import TipAdapter
from .cross_modal import CrossModalProbeAdapter
from .gaussian_per_class import GaussianPerClassAdapter
from .bayes_adapter import BayesAdapter
