from .base import BaseAdapter
from .random_probe import RandomProbeAdapter
from .zs_probe import ZeroShotProbeAdapter
from .task_residual import TaskResidualAdapter
from .clip_adapter import ClipAdapterResidual
from .tip_adapter import TipAdapter
from .cross_modal import CrossModalProbeAdapter
from .bayes_adapter import BayesAdapter
from .capel_adapter import CapelAdapter
from .vnccapel_adapter import VncCapelAdapter
from .ecka_adapter import ECKAAdapter
from .pp_proker_onehot import PPProKeROneHotAdapter
from .hba_lr_adapter import HbaLrAdapter
from .dream_bayes_adapter import DreamBayesAdapter
from .deba_adapter import DEBAAdapter
from .sbea_adapter import SBEAAdapter
from .bayes_adapter_plus import BayesAdapterPlus
from .rcv_bayes_adapter import RCVBayesAdapter
from .bayesian_task_residual_adapter import BayesianTaskResidualAdapter